
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZit3N21hZEhyUUF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeU1qQXdOVEExTWpGYUZ3MHpOakF5TVRnd05URXdNakZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURUMUhFM0RjbHBkb2JKQzVNSW5CZUFkNmh2alI2Qk9UUzhMQVRjK0NDUWloczhqMTJNTFBPcU9iakEKNXJIZm5MV2VkeVJ5QnQ5bm5jL0R6T0J4ZmNjMHZEZElQcXdCcEZxQ2t5R0dYd1ZZcmJ2a3RGUFNhZWdxQ3MxZwpiMzN0bmZKeStoUitlUmdMSFEzdnQzS1Z3QW1xd3BRZHRaeXQrU3UyZ1VXck5DYkgvOVRYcGcvTDdrUFBvZVg3ClFlRytUUnFkMjFZUUdTMFJvTzlmZlFQQ3hIYU51RHNwNzhiNWpyUWNuOHZETEp1Y0NJVGZQNmhxQXhoWWw2SVYKUEtweXd0ZnloRVYrMU9vd0lsVVYyQzYvY0RmZTllSk5rVWY0K1RuOHM1YjBGNW1qcHlpRi9MUi9pVmJCTC9sZQpXWVB3YTFJTnRJclJuWnVTUWZ0RFBjc1YrcXVYQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRakprdHI2SFpCcDFKZjRsQSs5Ry8xY0YzQmhEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUJIa2Q2OU5DVQpVaTYxK3MrazR6Q1ZzYXVpaWxIUDhQVjFmRFRta1Zlb1M2dHEwanc1R0tCd1VUejVBWHB6ZmY5a2I1QzgvaEFICld5ck1Wc0htN0NBWnJiS2N2S2RkZGVNN1drdGhFRHRNS3Faa3dEWGZLYkZtZGpBRXh0TFllbFMzWmRhcUJXajAKektiWmdZTFVyNHBHTm9ZVE5DRVhHNWFFaGxnai9sa1ExMmdkelVHY0ZUVGFIVVh1SmxreVlLQkxiN2xTSHN1dwo4UXMzZEZCM2VLSFRudWpXM2FaYmFDbG1PSStqejIzU2x4WlNOS05kalpHRDZPNkhvZlVKREY5c1dmNHR5U05VCkJmRHNkc0dmdlQ4U01PWGJ3QWx5T2NlLzl4clpnc1M4WGVzSDFkVTBzMTJhWHc0QVVkWk54aUlDWW1XSDRtVmsKZjQvajZSTFRsU1ZECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://80b4da47-f963-49c8-8e66-3882c478024d.us-west-1-gw.linodelke.net:443
  name: lke570982

users:
- name: lke570982-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjdlbnVoUlo2dGczNlVUTEJHN3NDOGRxVm5RRlczMlpqLUk2eVo0MHVhZGsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4teGh2eHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOTBhNjY2NTYtNTNiMy00OGM0LTlmYzgtM2M3Zjk2MDM0ODcwIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.pD70-okuop55BG6y-RNKwqNZq47OsZaaFD-DssTVkPOR8Jz_oqHJSvXgcwrsEI5aOUiizJODGyaQtYgkjyT2e7x1tm6oS5Rb4rjwywWkoVHpkWJPI_iOCeeBeF05qQ9oMCVuiGok3Rt4JBaRJHEmFMkt5Ld-hSCuxjMrnEnuPdbfoe2mk9WfTWxpZ9_XRXJA9WRbaMLnH_k-IEGbyUadev2XgP5yMEg-KtAW4QUkN4kdDXZhYKRUb_-ooZUsBr1o-Ixwcb1MrbZUUOAM3FbNjcO_s5V2WI6HgN9_WyisTMg4Wk3oPWUijzx_qPIJB6d4_LAdBZQlwvPTvWmwBuO37g

contexts:
- context:
    cluster: lke570982
    namespace: default
    user: lke570982-admin
  name: lke570982-ctx

current-context: lke570982-ctx
