apiVersion: v1
kind: Service
metadata:
  name: leaseguard-backend-svc
spec:
  selector:
    app: leaseguard-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
